This notebook explores the use of BentoML for managing and serving machine learning models.

In particular, it demonstrates how to:
- Import models from MLflow using the model name, version, or run ID.
- Load models that have already been imported into BentoML.
- Make predictions using a structured input schema defined with Pydantic.

In [3]:
import bentoml
import mlflow
from pydantic import BaseModel
import pandas as pd

In [4]:
mlflow.set_tracking_uri("http://localhost:5000")

In [4]:
class SpaceflightInput(BaseModel):
    engines: float
    passenger_capacity: int
    crew: float
    d_check_complete: bool
    moon_clearance_complete: bool
    iata_approved: bool
    company_rating: float
    review_scores_rating: float

## Load by model name and model version

In [5]:
bento_model = bentoml.mlflow.import_model(
    name="spaceflights-pandas",                 # <- set your <model_name>
    model_uri="models:/spaceflights-pandas/1"  # <- set your <model_name>/<model version>  
)

In [9]:
print(f"✅ Model imported with tag: {bento_model.tag}")

✅ Model imported with tag: spaceflights-pandas:wpdf4u5dswfuauc2


In [6]:
model = bentoml.mlflow.load_model(bento_model)

In [7]:
example_input = SpaceflightInput(
    engines=2,
    passenger_capacity=4,
    crew=1,
    d_check_complete=True,
    moon_clearance_complete=True,
    iata_approved=True,
    company_rating=4.5,
    review_scores_rating=8.0
)

df = pd.DataFrame([example_input.model_dump()]) 
model.predict(df)

array([2572.55859797])

## Load by model run ID

In [26]:
bento_model = bentoml.mlflow.import_model(
    name="spaceflights-pandas",                                 # <- set your <model_name>
    model_uri="runs:/44b8e990778b4415935497eab1d629d4/model"    # <- set your <run_id>
)

In [16]:
model = bentoml.mlflow.load_model(bento_model)

In [17]:
example_input = SpaceflightInput(
    engines=2,
    passenger_capacity=4,
    crew=1,
    d_check_complete=True,
    moon_clearance_complete=True,
    iata_approved=True,
    company_rating=4.5,
    review_scores_rating=8.0
)

df = pd.DataFrame([example_input.model_dump()]) 
model.predict(df)

array([2572.55859797])

## Load a model already imported in BentoML

Or by terminal: > bentoml models list

In [5]:
models = bentoml.models.list()
for m in models:
    print(f"{m.tag} | {m.info.module}")

237307bc466b40a3b0cdfa00b33666c8:20250916152035 | bentoml.mlflow
237307bc466b40a3b0cdfa00b33666c8:20250916153158 | bentoml.mlflow
237307bc466b40a3b0cdfa00b33666c8:20250916153716 | bentoml.mlflow
237307bc466b40a3b0cdfa00b33666c8:20250916155811 | bentoml.mlflow
237307bc466b40a3b0cdfa00b33666c8:20250916160258 | bentoml.mlflow
spaceflights-pandas:cjy3k4ncw2pt4uc2 | bentoml.mlflow
spaceflights-pandas:gclm375cwsm7muc2 | bentoml.mlflow
spaceflights-pandas:jgeyyu5cwspgouc2 | bentoml.mlflow
spaceflights-pandas:k3qhzlvcw2lhyuc2 | bentoml.mlflow
spaceflights-pandas:koqj7mfcwok5cuc2 | bentoml.mlflow
spaceflights-pandas:l7vooqncwwywkuc2 | bentoml.mlflow
spaceflights-pandas:nlp3z5fcxstxouc2 | bentoml.mlflow
spaceflights-pandas:nuvo6cfcwwmheuc2 | bentoml.mlflow
spaceflights-pandas:wpdf4u5dswfuauc2 | bentoml.mlflow


Take the model tag, to load model:

In [20]:
MLFLOW_MODEL_TAG = "spaceflights-pandas:k3qhzlvcw2lhyuc2"   # <- <model_tag> above
bento_model = bentoml.models.get(MLFLOW_MODEL_TAG)
model = bentoml.mlflow.load_model(bento_model)

In [21]:
example_input = SpaceflightInput(
    engines=2,
    passenger_capacity=4,
    crew=1,
    d_check_complete=True,
    moon_clearance_complete=True,
    iata_approved=True,
    company_rating=4.5,
    review_scores_rating=8.0
)

df = pd.DataFrame([example_input.model_dump()]) 
model.predict(df)

array([2572.55859797])

## List all BentoML Bento services
You find this reported in the docker-compose.yml file under the `training-inference` service and `deploy_monitoing-bentoml` service as image name:tag.

Or by terminal: > bentoml bentos list

In [8]:
bentos = bentoml.bentos.list()
for m in bentos:
    print(f"{m.tag} | {m.creation_time}")

spaceflight_service:3un65xfcxkxu6uc2 | 2025-10-06 13:46:32.255947+00:00
spaceflight_service:4o4tcdu632qpquc2 | 2025-10-01 15:54:19.764248+00:00
spaceflight_service:6o3aidm63o234uc2 | 2025-10-01 15:33:19.736378+00:00
spaceflight_service:kxnitcu63snmouc2 | 2025-10-01 15:36:02.264853+00:00
spaceflight_service:mswhk24632rowuc2 | 2025-10-01 15:50:46.659118+00:00
spaceflight_service:o72w5ufdq6c7guc2 | 2025-10-07 14:11:17.081954+00:00
specific_spaceflight_service:krixkm47nw326aav | 2025-10-02 08:53:57.925230+00:00
specific_spaceflight_service:sdarmcvcxwjo4uc2 | 2025-10-06 14:05:52.906852+00:00
specific_spaceflight_service:vtse5k5cp6ozyus2 | 2025-10-06 06:42:53.142014+00:00
specific_spaceflight_service:xqesotvds2nhuuc2 | 2025-10-07 16:00:27.407987+00:00
